language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- gem install compass
- bower install
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- grunt deploy
env:
  global:
    secure: Ib5e1gYzWbPRb3057VE25/XUeHQQCN3empIW+ZzZ3OTVHsfwGpIGTzvrfcFJciJRoYnXSt8W8C7D/ATOXN4HSzYcKKvYazITUlmVZbi3+EsgczhaFQGdcmMhuEMWfPU23iVif3RkP0Q6T55eNyK7sYoIo+tYAN4Uy2OOOOf9A5k=
